### ISSUE TITLE
JRE Exception Aborts CE-Symm Batch Calculations for Large Datasets

### ISSUE THREAD

**Issue by lafita** [rcsb/symmetry#87] opened 2016-06-17 15:47 UTC
When **CeSymm** is run in batch mode on large datasets (more than 60K structures) and using multiple threads (occurred with 4 and 8 threads so far), a **Java Runtime Environment Exception** aborts the calculation with an **hs_error** log message.

The error does not occur at the same point when using the same conditions, and using a single thread does not reproduce it. It is unlikely caused by a single structure or by a bug in the code, since all Java Exceptions are handled in **biojava** or the `CeSymmMain` script. 

Searching in the internet for the error did not give a hint on what the problem is, but it seems to be very low level and related to multi-threading.

**Comment by josemduarte** [comment] 2016-06-17 15:51
This reminds me of a problem we saw with the AFPChain alignment code. When compiled with the eclipse compiler we'd get a runtime error in one of the tests (without a core dump) whilst with default javac compiler tests would pass without problem. Perhaps it's nothing to do with this one, just want to drop the idea here for the record.

**Comment by lafita** [comment] 2016-06-17 16:16
The error seems very different, though. We have still the issue in #46 . If I remember correctly, that was a stochastic `IndexOutOfBoundsException`. 

Here it seems something more serious, because it happens with both compilers, in java8 and java7, in different machines and the program crashes without any Java `Exception`, but just a log file. 

I will try to reproduce the crash and copy the message in the log, but it looks cryptic and searching in the internet did not give any clue.

**Comment by josemduarte** [comment] 2016-06-17 16:26
Thanks for linking the issue, I didn't remember we had it! 

Anyway I suppose the crash you are seeing is a VM crash, which produces a core dump. Those are indeed difficult to debug and I doubt we can find much online. 

The multi-threading is some java multi-threaded code using java core libraries isn't it? Or is it spark?

**Comment by lafita** [comment] 2016-06-17 18:09
Yes, it is a VM crash with a core dump and very cryptic logging. The multithreading is using the **java.util.concurrent** library, which should be safe. I synchronized all file writing in the threads. However, they all share the same `AtomCache` to download the structures. Do you think this can be a problem? Maybe we should synchronize AtomCache downloads too.

**Comment by josemduarte** [comment] 2016-06-17 18:41
AtomCache is a singleton and we've seen many problems with it already in the past. I can perfectly see that could well be the issue here. Anyway we need a good test case that reproduces the issue or otherwise we can't do much about it.

**Comment by josemduarte** [comment] 2016-06-17 18:46
Correction (thanks @andreasprlic ): the singleton is the AtomCache static variable in `StructureIO`, not AtomCache itself.

**Comment by andreasprlic** [comment] 2016-06-17 18:59
Are you using StructureIO? We perhaps have to create a new instance of AtomCache every time a structure gets requested, or otherwise synchronize access to the Structure object in getStructure. That probably means we need to find a way to configure FileParsingParameters, so the user can influence the behavior.

**Comment by lafita** [comment] 2016-06-20 08:18
@andreasprlic I am using a single `AtomCache` object shared by all threads. I would not change `StructureIO` until we are certain that the error is caused by a synchronization issue in `AtomCache`.

The error also appeared when using a single thread, but only in **SCOP** domains. **CATH** and **ECOD** domains finished without errors. The error message is the following:

<pre>
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (safepoint.cpp:314), pid=3413, tid=139801578661632
#  guarantee(PageArmed == 0) failed: invariant
#
# JRE version: OpenJDK Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.91-b14 mixed mode linux-amd64 compressed oops)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /afs/psi.ch/user/l/lafita_a/symmetry-census/hs_err_pid3413.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted
</pre>

**Comment by sbliven** [comment] 2016-06-20 08:43
IMO it's unlikely to be an AtomCache problem because all the threads will be downloading different structures and shouldn't be setting any cache parameters, so they should run completely independently. We could verify this by synchronizing all setters on the `currentlyLoading` member, but it's probably not the source of the bug.

`PageArmed == 0` makes it seem like a memory bug. Maybe explicitly calling `System.gc()` regularly might reduce the frequency of crashes?

**Comment by andreasprlic** [comment] 2016-06-20 17:03
You could do this test: In StructureIO, create a new AtomCache every time you call getStructure(). (and set the file parsing parameters from the static copy). If this fixes your problem, it is a synchronization issue..

**Comment by sbliven** [comment] 2018-06-04 11:47
Closing as a likely VM bug

**Closed by sbliven** 2018-06-04 11:47 UTC
Labels: bug, wontfix
